os: osx
language: node_js
node_js:
  - "10"
notifications:
    email: false
cache:
  timeout: 600000
  directories:
    - deps

install:
  - brew install icu4c && brew link icu4c --force
  - export PATH=$PATH:$PWD/tools/depot_tools
  - npm i -g eslint babel-eslint eslint-config-airbnb eslint-plugin-import eslint-plugin-react eslint-plugin-jsx-a11y

script:
  - ./configure --expose-binding
  - make test

