os: osx
language: node_js
node_js:
  - "10"
notifications:
    email: false
cache:
  directories:
    - deps

install:
  - export PATH=$PATH:$PWD/tools/depot_tools
  - npm i -g eslint babel-eslint eslint-config-airbnb eslint-plugin-import eslint-plugin-react eslint-plugin-jsx-a11y

script:
  - make test

